src/Entity/DetailCommande.php
<?php

namespace App\Entity;

use App\Repository\DetailCommandeRepository;


use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DetailCommandeRepository::class)
 */
class DetailCommande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantite;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\ManyToOne(targetEntity=Commande::class, inversedBy="detailCommandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $commande;

    /**
     * @ORM\ManyToOne(targetEntity=Produit::class, inversedBy="detailCommandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produit;

    

    

    

  

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(int $Quantite): self
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->commande;
    }

    public function setCommande(?Commande $commande): self
    {
        $this->commande = $commande;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    

    

    

}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Repository\ProduitRepository;
use App\Service\Panier\CartService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 *
 * @IsGranted("ROLE_CLIENT")
 */
class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="cart")
     */
    public function index(CartService $serviceCart): Response
    {

        $user = $this->getUser();
        
        
        
        
        return $this->render('cart/index.html.twig', [
            'cart'=>$serviceCart->getFullCart(),
            'total' => $serviceCart->getTotal(),
            'tax' => ($serviceCart->getTotal()*18)/100
        ]);
    }

    /**
     * @Route("/cart/add/{code}", name="cart_add")
     */

    public function add($code, CartService $serviceCart){

        $user = $this->getUser();
        
      

        $serviceCart->add($code);
        return $this->redirectToRoute('cart');

    }

    /**
     * @Route("/cart/remove/{code}", name="cart_remove")
     */

    public function remove($code, CartService $serviceCart){

        $user = $this->getUser();
        
        

        $serviceCart->remove($code);
        return $this->redirectToRoute('cart');

    }
    
    /**
     * @Route("/cart/remove/item/{code}", name="cart_remove_item")
     */

    public function removeQuantite($code, CartService $serviceCart){

        $user = $this->getUser();
        
        if(in_array("ROLE_GESTIONNAIRE", $user->getRoles())){
            
            return $this->redirectToRoute('dashboard');
            
        }

        $serviceCart->removeItemQuantite($code);
        return $this->redirectToRoute('cart');

    } 
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if cart | length == 0 %} 
	<h2 class="text-center">Votre panier est vide </h2>
	<br>
	<div class="text-center">
		<a href="" class="btn btn-primary">Acheter un burger</a>
	</div>
   {% else %}
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
      {% for item in cart %} 
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{asset('uploads/product/')}}{{item.item.image}}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="" class="title text-dark">{{item.item.nom}}</a>
                    {# <p class="text-muted small">Color: 25 Mpx <br> Size: Canon</p> #}
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
            <div class="col"> 
                <div class="input-group input-spinner">
                    <div class="input-group-prepend">
                    <a href="{{path('cart_remove_item',{code:item.item.code})}}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                    </div>
                    <input type="text" class="form-control"  value="{{item.quantite}}">
                    <div class="input-group-append">
                    <a href="{{path('cart_add',{code:item.item.code})}}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
                    </div>
                </div> <!-- input-group.// -->
            </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">{{item.item.prix * item.quantite}} CFA</var> 
                <small class="text-muted"> {{item.item.prix}} CFA</small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
            <a href="{{path('cart_remove',{code:item.item.code})}}" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
   {% endfor %}
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">{{total}} CFA </dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> {{tax}} CFA </dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total: </dt>
                  <dd class="text-right text-dark b"><strong>{{ total + tax }}  CFA</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="" height="26">
                </p>
                <a href="{{path('checkout')}}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
   {% endif %} 
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
{% endblock %}